services:
  app:
    image: ituacm_website:latest
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.website-app.loadbalancer.server.port=80

      - traefik.http.routers.website-app-http.rule=Host(`${DOMAIN?Variable not set}`) || Host(`www.${DOMAIN?Variable not set}`)
      - traefik.http.routers.website-app-http.entrypoints=http

      - traefik.http.routers.website-app-https.rule=Host(`${DOMAIN?Variable not set}`) || Host(`www.${DOMAIN?Variable not set}`)
      - traefik.http.routers.website-app-https.entrypoints=https
      - traefik.http.routers.website-app-https.tls=true
      - traefik.http.routers.website-app-https.tls.certresolver=le

      # Enable www redirection for HTTP and HTTPS
      - traefik.http.routers.website-app-http.middlewares=https-redirect
    networks:
      - traefik-public
      - default
    build:
      context: .
    platform: linux/amd64 # Patch for M1 Mac

networks:
  traefik-public:
    external: true
